### PR TITLE
feat: add package for sealed-secrets controller

### PR DESCRIPTION
**Pull request by Baalekshan**
Added sealed-secrets controller to packages

### CODE REVIEW

**Review by pmig — CHANGES_REQUESTED** [review]
Thanks for adding sealed secrets.

We just added a reference to the ArtifactHub url for all other packages, so we should add it here as well. See: https://github.com/glasskube/packages/commit/959e789b15e44eee01a755a6bf533592370d9026

**Review by kosmoz — CHANGES_REQUESTED** [review]
Works great! Here are two suggestions:

1. We use a [build identifier](https://semver.org/#spec-item-10) to allow distinction between package versions of the same app version. Please change `v2.15.3` to `v2.15.3+1` everywhere (also the directory name)
2. I think we should add a sentence to the long description about how to use this package effectively:
   ```
   To use this package, install the [kubeseal](https://github.com/bitnami-labs/sealed-secrets#kubeseal) application. 
   Use kubeseal with the `--controller-namespace=sealed-secrets-system` flag. 
   For more information, check out the [official documentation](https://github.com/bitnami-labs/sealed-secrets#usage).
   ```

**Review by pmig — APPROVED** [review]

**Comment by pmig** [comment]
@Baalekshan LGTM could you please rebase the PR and squasch your changes to a single commit?

:pray: Thanks a million

**Comment by pmig** [comment]
close / open was a mistake on my side

**Comment by Baalekshan** [comment]
> @Baalekshan LGTM could you please rebase the PR and squasch your changes to a single commit?
> 
> 🙏 Thanks a million

@pmig I have squashed the commits

**Pull request merged**
